# Edge Function configuration for widget-analytics
# Allow anonymous (no JWT) requests so public widgets can fetch analytics.
verify_jwt = false
# Add legacy / alternative flags for older or transitional runtimes (harmless if ignored)
jwt_verification = false
jwt_verify = false

# (Optional) You can later scope allowed origins at the application layer.
# NOTE: If 401 responses still appear with body {"code":401,"message":"Missing authorization header"}
# that indicates the platform layer is intercepting before the function. In that case confirm in the
# Supabase Dashboard: Settings > API > Edge Functions that project-level JWT enforcement is disabled
# or per-function override is supported for your project region/runtime.
