import { WidgetConfig, WidgetType } from './types';

export const getDefaultConfig = (type: WidgetType): WidgetConfig => ({
  theme: 'light',
  primaryColor: type === 'booking' ? '#3b82f6' : '#f97316',
  secondaryColor: type === 'booking' ? '#1e40af' : '#ea580c',
  backgroundColor: '#ffffff',
  textColor: '#1f2937',
  borderRadius: 8,
  borderWidth: 1,
  borderColor: '#e5e7eb',
  shadowIntensity: 2,
  fontFamily: 'system',
  fontSize: 14,
  fontWeight: 'normal',
  lineHeight: 1.5,
  welcomeMessage: type === 'booking' ? 'Book your table with us!' : 'Order catering for your event!',
  description: type === 'booking' ? 'Reserve your perfect dining experience' : 'Delicious catering for any occasion',
  buttonText: type === 'booking' ? 'Reserve Now' : 'Order Catering',
  footerText: 'Powered by Blunari',
  width: 400,
  height: 600,
  padding: 20,
  spacing: 16,
  alignment: 'center',
  size: 'medium',
  showLogo: true,
  showDescription: true,
  showFooter: true,
  compactMode: false,
  enableAnimations: true,
  animationType: 'fade',
  enableTableOptimization: type === 'booking',
  showAvailabilityIndicator: true,
  requireDeposit: false,
  enableSpecialRequests: true,
  showDurationSelector: type === 'booking',
  enablePhoneBooking: true,
  maxPartySize: type === 'booking' ? 12 : 50,
  minAdvanceBooking: 1,
  maxAdvanceBooking: 30,
  customCss: '',
  customJs: '',
  isEnabled: true,
  bookingSource: 'widget',
  autoFocus: true,
  closeOnOutsideClick: true,
  showCloseButton: true,
});
