// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase environment variables. Please check .env file.");
  
  // In development, provide fallback values to prevent app crash
  if (import.meta.env.MODE === 'development') {
    console.warn("Using fallback Supabase configuration for development");
  } else {
    throw new Error("Missing Supabase environment variables. Please check .env file.");
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || "https://placeholder.supabase.co",
  SUPABASE_PUBLISHABLE_KEY || "placeholder-key",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      debug: import.meta.env.MODE === 'development' && import.meta.env.VITE_ENABLE_SUPABASE_DEBUG === 'true',
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
      // Use defaults that are friendlier to browser idle/visibility changes
      heartbeatIntervalMs: 30000, // Increased to reduce connection churn
      reconnectAfterMs: (tries: number) => Math.min(tries * 5000, 120000), // More conservative backoff
      // Use default WebSocket transport (string value is invalid in v2 and causes constructor error)
      timeout: 20000,
      // Graceful degradation when WebSocket fails
      logger: (level: string, message: string, details?: any) => {
        if (level === 'error' && message.includes('WebSocket')) {
          // Suppress noisy WebSocket errors in console unless debug enabled
          if (import.meta.env.VITE_ENABLE_SUPABASE_DEBUG === 'true') {
            console.warn('[Supabase Realtime]', message, details);
          }
        } else if (import.meta.env.MODE === 'development') {
          console.log('[Supabase Realtime]', level, message, details);
        }
      }
    },
    global: {
      fetch: (url, options = {}) => {
        const enableVerbose = import.meta.env.MODE === 'development' && import.meta.env.VITE_ENABLE_SUPABASE_DEBUG === 'true';
        const method = (options as any).method || 'GET';
        if (enableVerbose) {
          console.log('[Supabase] Request:', { url, method });
        }
        return fetch(url, { ...(options as any), keepalive: false }).then(async res => {
          if (enableVerbose) {
            let bodyPreview: string | undefined;
            if (!res.ok && res.headers.get('content-type')?.includes('application/json')) {
              try {
                const clone = res.clone();
                const txt = await clone.text();
                bodyPreview = txt.slice(0, 400);
              } catch {}
            }
            console.log('[Supabase] Response:', { url, status: res.status, ok: res.ok, preview: bodyPreview });
          }
          // Extra targeted diagnostics for widget-analytics 400s
          if (!res.ok && /\/functions\/v1\/widget-analytics$/.test(url) && res.status === 400) {
            try {
              const clone = res.clone();
              const txt = await clone.text();
              console.warn('[WidgetAnalytics][HTTP 400] Raw body:', txt.slice(0, 1000));
            } catch (e) {
              console.warn('[WidgetAnalytics][HTTP 400] Failed to read error body', e);
            }
          }
          return res;
        });
      },
    },
  },
);
